application: js-fireworks
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: canvas/index.html
  upload: canvas/index.html
- url: /(.*)
  static_files: \1
  upload: (.*)
